/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    properties: Property;
    posts: Post;
    categories: Category;
    'blog-topics': BlogTopic;
    media: Media;
    enquiries: Enquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'blog-topics': BlogTopicsSelect<false> | BlogTopicsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every property listed on the website. Fill in the form, upload photographs, then press Publish. Save Draft keeps it hidden from the website until you are ready.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  /**
   * e.g. "Builder Floor, Greater Kailash II · Second Level"
   */
  title: string;
  /**
   * e.g. Greater Kailash, Lajpat Nagar, Jangpura
   */
  locality: string;
  location?: string | null;
  propertyType: 'builder-floor' | 'pre-owned-floor' | 'independent-house' | 'office-space' | 'plot';
  listingType: 'sale' | 'rent' | 'collaboration';
  availability: 'available' | 'under-offer' | 'under-construction' | 'sold' | 'rented';
  /**
   * e.g. 4 BHK + Study
   */
  configuration?: string | null;
  /**
   * e.g. 2,150 sq ft
   */
  area?: string | null;
  /**
   * e.g. Second of four
   */
  floor?: string | null;
  /**
   * e.g. East · Park facing
   */
  facing?: string | null;
  /**
   * Shown as written, e.g. "₹ 4.25 Cr" or "₹ 3.45 Lakh / month". Leave blank for "On request".
   */
  price?: string | null;
  /**
   * e.g. Negotiable · All inclusive
   */
  priceNote?: string | null;
  featured?: boolean | null;
  /**
   * The main write-up shown on the property page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short, factual lines, e.g. "Private lift lobby on every floor".
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Lift, Stilt parking, Power backup, Terrace rights
   */
  amenities?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Label and value pairs shown in the specification table, e.g. "Parking" / "2 covered".
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The lead image on cards and at the top of the property page.
   */
  heroImage?: (number | null) | Media;
  /**
   * Drag the rows to reorder. The order here is the order on the website.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        /**
         * e.g. Second floor · 2,150 sq ft
         */
        label?: string | null;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube or Vimeo link for a walkthrough film, if available.
   */
  videoUrl?: string | null;
  /**
   * Or upload an MP4/WebM directly (keep it under ~50 MB).
   */
  videoFile?: (number | null) | Media;
  seo?: {
    /**
     * Leave blank to use the property name.
     */
    metaTitle?: string | null;
    /**
     * One or two sentences, under 160 characters.
     */
    metaDescription?: string | null;
    /**
     * Leave blank to use the cover photograph.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * The web address, e.g. "builder-floor-greater-kailash-2". Leave blank to generate from the name.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All images and files used across the website. Upload once, reuse anywhere. Always fill in the description so search engines and screen readers understand the image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows, e.g. "Marble-clad living room of a Greater Kailash builder floor".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Articles for the News & Blogs section. Save Draft to keep writing, Publish when it should go live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  category?: (number | null) | Category;
  publishedDate?: string | null;
  /**
   * The lead image, shown on cards and at the top of the article. Articles without one still publish, but adding an image makes the page eligible for image-rich search results.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Written by the automatic writer as a starting point for the featured image. Paste it into your image tool, then upload the result above. Internal only: never shown on the website.
   */
  imageBrief?: string | null;
  /**
   * A one or two sentence summary shown on listing cards.
   */
  excerpt?: string | null;
  /**
   * Three or four short, self-contained points shown in a summary box at the top of the article. Search and AI answer engines quote these directly, so each one should make sense on its own, without the surrounding article.
   */
  keyTakeaways?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown at the end of the article and published as FAQ structured data, which is what AI answer engines quote. Keep answers short and factual.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The byline shown on the article.
   */
  author?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Leave blank to use the post title.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Leave blank to generate from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Categories for organising blog posts, e.g. Market Notes, Guides, Firm News.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The queue the automatic writer works through. Add topics you want covered; the next scheduled post (Monday and Saturday) takes the oldest one still marked Queued. If the queue is empty the writer falls back to its own South Delhi property topics, so the site never goes quiet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-topics".
 */
export interface BlogTopic {
  id: number;
  /**
   * e.g. "How stilt parking rights are allocated in a builder floor rebuild"
   */
  topic: string;
  /**
   * Optional. Anything the article must cover or avoid, in plain English. Passed to the writer as instructions.
   */
  angle?: string | null;
  status?: ('queued' | 'published' | 'skipped') | null;
  usedAt?: string | null;
  /**
   * The article generated from this topic.
   */
  post?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted through the website contact form. Update the status as you work through them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  firstName: string;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * Filled in automatically when the enquiry came from a property page.
   */
  property?: (number | null) | Property;
  consent?: boolean | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  /**
   * Internal notes. Never shown on the website.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'blog-topics';
        value: number | BlogTopic;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  locality?: T;
  location?: T;
  propertyType?: T;
  listingType?: T;
  availability?: T;
  configuration?: T;
  area?: T;
  floor?: T;
  facing?: T;
  price?: T;
  priceNote?: T;
  featured?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  videoUrl?: T;
  videoFile?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishedDate?: T;
  featuredImage?: T;
  imageBrief?: T;
  excerpt?: T;
  keyTakeaways?:
    | T
    | {
        point?: T;
        id?: T;
      };
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-topics_select".
 */
export interface BlogTopicsSelect<T extends boolean = true> {
  topic?: T;
  angle?: T;
  status?: T;
  usedAt?: T;
  post?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  property?: T;
  consent?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, legal text and other site-wide content. Changes here update every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The full address as it should read on the site, e.g. I-9, Basement (Cabin No. 1), Lajpat Nagar - 1, New Delhi - 110024
   */
  address?: string | null;
  /**
   * The main number, e.g. +91-9891821130
   */
  phone?: string | null;
  /**
   * Optional. Shown alongside the main number.
   */
  phoneSecondary?: string | null;
  email?: string | null;
  /**
   * Digits only with country code, e.g. 919812345678. Leave blank to hide the WhatsApp link.
   */
  whatsapp?: string | null;
  /**
   * e.g. Mon to Sat, 10:00 to 19:00
   */
  officeHours?: string | null;
  /**
   * Optional. From Google Maps: Share, Embed a map, copy only the src link.
   */
  mapEmbedUrl?: string | null;
  /**
   * NOTE: the original brief supplied consent text that referred to "Rana Infra", which does not match the A2S Estates brand. It has been rewritten for A2S Estates. Replace this with your legally approved wording.
   */
  consentText?: string | null;
  copyrightName?: string | null;
  socialLinks?:
    | {
        platform?: ('Instagram' | 'Facebook' | 'LinkedIn' | 'YouTube' | 'X') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  address?: T;
  phone?: T;
  phoneSecondary?: T;
  email?: T;
  whatsapp?: T;
  officeHours?: T;
  mapEmbedUrl?: T;
  consentText?: T;
  copyrightName?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}